"""empty message

Revision ID: 03d063ccdd59
Revises: 
Create Date: 2019-04-18 07:14:30.045211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03d063ccdd59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('notepad_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'note', 'notepad', ['notepad_id'], ['note_pad_id'])
    op.drop_constraint(u'users_note_book_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'posts')
    op.drop_column('users', 'note_book')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('note_book', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('posts', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'users_note_book_fkey', 'users', 'notepad', ['note_book'], ['note_pad_id'])
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.drop_column('note', 'notepad_id')
    # ### end Alembic commands ###
